/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.view;

/**
 *
 * @author ThiagoAugustus
 */
public class LoginView extends javax.swing.JInternalFrame {

     /**
     * Metodo construtor
     * @param mv 
     */
    public LoginView(MainView mv) {
        initComponents();
        mv.nome = "asas";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelLocker = new javax.swing.JLabel();
        labelHotel = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        inputLogin = new javax.swing.JTextField();
        labelDesc = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        btAccess = new javax.swing.JButton();

        labelLocker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-lock.png"))); // NOI18N

        labelHotel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelHotel.setForeground(new java.awt.Color(153, 153, 153));
        labelHotel.setText("Hotel");

        labelLogin.setText("Login");

        labelPass.setText("Senha");

        labelDesc.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelDesc.setForeground(new java.awt.Color(153, 153, 153));
        labelDesc.setText("Área Administrativa");

        btAccess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-login.png"))); // NOI18N
        btAccess.setToolTipText("Acessar sistema");
        btAccess.setMaximumSize(new java.awt.Dimension(40, 40));
        btAccess.setMinimumSize(new java.awt.Dimension(40, 40));
        btAccess.setPreferredSize(new java.awt.Dimension(40, 40));
        btAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLocker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDesc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPass)
                            .addComponent(labelLogin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputLogin)
                            .addComponent(inputPass)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHotel)
                            .addComponent(labelDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLogin)
                            .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPass)
                            .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLocker)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccessActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btAccessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccess;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelHotel;
    private javax.swing.JLabel labelLocker;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPass;
    // End of variables declaration//GEN-END:variables
}
