package br.edu.unifil.view;

import br.edu.unifil.model.PerfilModel;
import br.edu.unifil.model.PermissaoModel;
import br.edu.unifil.model.UsuarioModel;

public class MainView extends javax.swing.JFrame {

    private ReservaView reservaView = null;
    private QuartoView  quartoView  = null;
    private UsuarioModel usuario;
    
    public MainView() {
        initComponents();
        
        // Usuario teste
        this.usuario = new UsuarioModel();
        PerfilModel perfil = new PerfilModel();
        PermissaoModel permissoes = new PermissaoModel();
        permissoes.setReadPermissao(true);
        permissoes.setCreatePermissao(true);
        permissoes.setUpdatePermissao(true);
        permissoes.setDeletePermissao(false);
        perfil.setPermissaoPerfil(permissoes);
        this.usuario.setPerfilUsuario(perfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPrincipal = new javax.swing.JDesktopPane();
        painelInfoPrincipal = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelUsuarioNome = new javax.swing.JLabel();
        labelLog = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        btReserva = new javax.swing.JMenu();
        btReservaFazer = new javax.swing.JMenuItem();
        btQuarto = new javax.swing.JMenu();
        btQuartoConsultar = new javax.swing.JMenuItem();
        btMenu = new javax.swing.JMenu();
        btPermissao = new javax.swing.JMenuItem();
        btUsuario = new javax.swing.JMenuItem();
        btSistema = new javax.swing.JMenu();
        btAjuda = new javax.swing.JMenuItem();
        btSobre = new javax.swing.JMenuItem();
        btSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GospelWay Hotel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        desktopPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        painelInfoPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        painelInfoPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        labelUsuario.setText("Usuario");

        labelUsuarioNome.setBackground(new java.awt.Color(255, 255, 255));
        labelUsuarioNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuarioNome.setForeground(new java.awt.Color(102, 102, 102));
        labelUsuarioNome.setText("Thiago Augustus de Oliveira");

        labelLog.setBackground(new java.awt.Color(255, 255, 255));
        labelLog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLog.setForeground(new java.awt.Color(102, 102, 102));
        labelLog.setText("Login 24/06/2013 23:56:22");

        javax.swing.GroupLayout painelInfoPrincipalLayout = new javax.swing.GroupLayout(painelInfoPrincipal);
        painelInfoPrincipal.setLayout(painelInfoPrincipalLayout);
        painelInfoPrincipalLayout.setHorizontalGroup(
            painelInfoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsuarioNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(labelLog)
                .addContainerGap())
        );
        painelInfoPrincipalLayout.setVerticalGroup(
            painelInfoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelUsuario)
                .addComponent(labelUsuarioNome)
                .addComponent(labelLog))
        );

        painelInfoPrincipal.setBounds(0, 570, 800, 20);
        desktopPrincipal.add(painelInfoPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btReserva.setText("Reserva");

        btReservaFazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        btReservaFazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-reserve.png"))); // NOI18N
        btReservaFazer.setText("Fazer Reserva");
        btReservaFazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservaFazerActionPerformed(evt);
            }
        });
        btReserva.add(btReservaFazer);

        menuPrincipal.add(btReserva);

        btQuarto.setText("Quarto");

        btQuartoConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btQuartoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-room.png"))); // NOI18N
        btQuartoConsultar.setText("Consultar");
        btQuartoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuartoConsultarActionPerformed(evt);
            }
        });
        btQuarto.add(btQuartoConsultar);

        menuPrincipal.add(btQuarto);

        btMenu.setText("Admin");

        btPermissao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        btPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-permission.png"))); // NOI18N
        btPermissao.setText("Permissões");
        btMenu.add(btPermissao);

        btUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-user.png"))); // NOI18N
        btUsuario.setText("Usuários");
        btMenu.add(btUsuario);

        menuPrincipal.add(btMenu);

        btSistema.setText("Sistema");

        btAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        btAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-help.png"))); // NOI18N
        btAjuda.setText("Ajuda");
        btSistema.add(btAjuda);

        btSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        btSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-info.png"))); // NOI18N
        btSobre.setText("Sobre");
        btSistema.add(btSobre);

        btSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-quit.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setToolTipText("Sair do programa");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        btSistema.add(btSair);

        menuPrincipal.add(btSistema);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairMouseClicked

    private void btReservaFazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservaFazerActionPerformed
        // TODO add your handling code here:
        if ( this.reservaView == null || this.reservaView.isClosed() ) {
            this.reservaView = new ReservaView(this.usuario);
            desktopPrincipal.add(this.reservaView);
            this.reservaView.setVisible(true);
        } else {
            System.out.println("Não é possivel criar uma nova instância!");
        }
    }//GEN-LAST:event_btReservaFazerActionPerformed

    private void btQuartoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuartoConsultarActionPerformed
        // TODO add your handling code here:
        if ( this.quartoView == null || this.quartoView.isClosed() ) {
            this.quartoView = new QuartoView(this.usuario);
            desktopPrincipal.add(this.quartoView);
            this.quartoView.setVisible(true);
        } else {
            System.out.println("Não é possivel criar uma nova instância!");
        }
    }//GEN-LAST:event_btQuartoConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAjuda;
    private javax.swing.JMenu btMenu;
    private javax.swing.JMenuItem btPermissao;
    private javax.swing.JMenu btQuarto;
    private javax.swing.JMenuItem btQuartoConsultar;
    private javax.swing.JMenu btReserva;
    private javax.swing.JMenuItem btReservaFazer;
    private javax.swing.JMenuItem btSair;
    private javax.swing.JMenu btSistema;
    private javax.swing.JMenuItem btSobre;
    private javax.swing.JMenuItem btUsuario;
    private javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuarioNome;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel painelInfoPrincipal;
    // End of variables declaration//GEN-END:variables
}
