/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.view;

import br.edu.unifil.model.PerfilModel;
import br.edu.unifil.model.PermissaoModel;
import br.edu.unifil.model.QuartoModel;
import br.edu.unifil.model.TipoQuartoModel;
import br.edu.unifil.model.UsuarioModel;

/**
 *
 * @author ThiagoAugustus
 */
public class QuartoView extends javax.swing.JInternalFrame {

    private UsuarioModel    usuario;
    private QuartoModel     quarto;
    private TipoQuartoModel tipoQuarto;
    
    /**
     * Classe construtora
     * @param usuario 
     */
    public QuartoView(UsuarioModel usuario) {
        initComponents();
        
        // Valida o usuario
        this.usuario = usuario;
        validaUsuario( this.usuario.getPerfilUsuario() );
        
        // Inicializa os atributos
        this.quarto     = new QuartoModel();
        this.tipoQuarto = new TipoQuartoModel();
        
    }
    
    /**
     * Valida as permissoes
     * @param perfil 
     */
    private void validaUsuario(PerfilModel perfil){
        
        // Recupera a permissao
        PermissaoModel permissoes = perfil.getPermissaoPerfil();
        
        // Verifica as permissoes
        if ( !permissoes.isReadPermissao() ){
            this.tabelaQuartos.setVisible(false);
        }
        if ( !permissoes.isUpdatePermissao() ){
            this.btEdite.setVisible(false);
        }
        if ( !permissoes.isCreatePermissao() ){
            this.btCreate.setVisible(false);
        }
        if ( !permissoes.isDeletePermissao() ){
            this.btDelete.setVisible(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaQuartos = new javax.swing.JTable();
        inputId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelQuartosCadastrados = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        inputDescricao = new javax.swing.JTextField();
        labelCapacidade = new javax.swing.JLabel();
        labelTipoQuarto = new javax.swing.JLabel();
        inputTipoQuartoCombo = new javax.swing.JComboBox();
        btCreate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btEdite = new javax.swing.JButton();
        inputCapacidade = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Quartos");
        setToolTipText("");

        tabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N", "Capacidade", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaQuartos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaQuartos);

        inputId.setEnabled(false);
        inputId.setFocusable(false);

        jLabel1.setText("ID");

        labelQuartosCadastrados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelQuartosCadastrados.setText("Quartos Cadastrados");

        labelDescricao.setText("Descrição");

        labelCapacidade.setText("Capacidade");

        labelTipoQuarto.setText("Tipo");

        inputTipoQuartoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-ok.png"))); // NOI18N
        btCreate.setToolTipText("Cadastrar quarto");
        btCreate.setMaximumSize(new java.awt.Dimension(60, 60));
        btCreate.setMinimumSize(new java.awt.Dimension(60, 60));
        btCreate.setPreferredSize(new java.awt.Dimension(60, 60));

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-delete.png"))); // NOI18N
        btDelete.setToolTipText("Excluir quarto");
        btDelete.setMaximumSize(new java.awt.Dimension(60, 60));
        btDelete.setMinimumSize(new java.awt.Dimension(60, 60));
        btDelete.setPreferredSize(new java.awt.Dimension(60, 60));

        btEdite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/unifil/image/ic-edit.png"))); // NOI18N
        btEdite.setToolTipText("Atualizar quarto");
        btEdite.setMaximumSize(new java.awt.Dimension(60, 60));
        btEdite.setMinimumSize(new java.awt.Dimension(60, 60));
        btEdite.setPreferredSize(new java.awt.Dimension(60, 60));

        inputCapacidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTipoQuarto)
                                .addGap(44, 44, 44)
                                .addComponent(inputTipoQuartoCombo, 0, 163, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(inputDescricao)))
                        .addGap(18, 18, 18)
                        .addComponent(labelCapacidade)
                        .addGap(18, 18, 18)
                        .addComponent(inputCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btEdite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuartosCadastrados)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCapacidade)
                    .addComponent(inputCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoQuarto)
                    .addComponent(inputTipoQuartoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelQuartosCadastrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEdite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 405, 371);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdite;
    private javax.swing.JFormattedTextField inputCapacidade;
    private javax.swing.JTextField inputDescricao;
    private javax.swing.JTextField inputId;
    private javax.swing.JComboBox inputTipoQuartoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCapacidade;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelQuartosCadastrados;
    private javax.swing.JLabel labelTipoQuarto;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTable tabelaQuartos;
    // End of variables declaration//GEN-END:variables
}
